declare module "*.png";
declare module "*.jpeg";
declare module "*.jpg";
declare module "*.svg";
declare module "*.mp3";
declare module "*.woff";
declare module "*.otf";
declare module "*.woff2";
declare module "*.ttf";
