// BrailleMapping.tsx

type BrailleMapping = {
  [key: string]: {
    braille: string;
    keyMapping: number;
  };
};

// Initialize and declare the ASCII to Braille map
export const asciiBraille: BrailleMapping = {
  "0": { braille: "⠴", keyMapping: 52 },
  "1": { braille: "⠂", keyMapping: 2 },
  "2": { braille: "⠆", keyMapping: 6 },
  "3": { braille: "⠒", keyMapping: 18 },
  "4": { braille: "⠲", keyMapping: 50 },
  "5": { braille: "⠢", keyMapping: 34 },
  "6": { braille: "⠖", keyMapping: 22 },
  "7": { braille: "⠶", keyMapping: 54 },
  "8": { braille: "⠦", keyMapping: 38 },
  "9": { braille: "⠔", keyMapping: 20 },
  " ": { braille: "⠀", keyMapping: 0 },
  "!": { braille: "⠮", keyMapping: 46 },
  '"': { braille: "⠐", keyMapping: 16 },
  "#": { braille: "⠼", keyMapping: 60 },
  $: { braille: "⠫", keyMapping: 43 },
  "%": { braille: "⠩", keyMapping: 41 },
  "&": { braille: "⠯", keyMapping: 47 },
  "'": { braille: "⠄", keyMapping: 4 },
  "(": { braille: "⠷", keyMapping: 55 },
  ")": { braille: "⠾", keyMapping: 62 },
  "*": { braille: "⠡", keyMapping: 33 },
  "+": { braille: "⠬", keyMapping: 44 },
  ",": { braille: "⠠", keyMapping: 32 },
  "-": { braille: "⠤", keyMapping: 36 },
  ".": { braille: "⠨", keyMapping: 40 },
  "/": { braille: "⠌", keyMapping: 12 },
  ":": { braille: "⠱", keyMapping: 49 },
  ";": { braille: "⠰", keyMapping: 48 },
  "<": { braille: "⠣", keyMapping: 35 },
  "=": { braille: "⠿", keyMapping: 63 },
  ">": { braille: "⠜", keyMapping: 28 },
  "?": { braille: "⠹", keyMapping: 57 },
  "@": { braille: "⠈", keyMapping: 8 },
  a: { braille: "⠁", keyMapping: 1 },
  b: { braille: "⠃", keyMapping: 3 },
  c: { braille: "⠉", keyMapping: 9 },
  d: { braille: "⠙", keyMapping: 25 },
  e: { braille: "⠑", keyMapping: 17 },
  f: { braille: "⠋", keyMapping: 11 },
  g: { braille: "⠛", keyMapping: 27 },
  h: { braille: "⠓", keyMapping: 19 },
  i: { braille: "⠊", keyMapping: 10 },
  j: { braille: "⠚", keyMapping: 26 },
  k: { braille: "⠅", keyMapping: 5 },
  l: { braille: "⠇", keyMapping: 7 },
  m: { braille: "⠍", keyMapping: 13 },
  n: { braille: "⠝", keyMapping: 29 },
  o: { braille: "⠕", keyMapping: 21 },
  p: { braille: "⠏", keyMapping: 15 },
  q: { braille: "⠟", keyMapping: 31 },
  r: { braille: "⠗", keyMapping: 23 },
  s: { braille: "⠎", keyMapping: 14 },
  t: { braille: "⠞", keyMapping: 30 },
  u: { braille: "⠥", keyMapping: 37 },
  v: { braille: "⠧", keyMapping: 39 },
  w: { braille: "⠺", keyMapping: 58 },
  x: { braille: "⠭", keyMapping: 45 },
  y: { braille: "⠽", keyMapping: 61 },
  z: { braille: "⠵", keyMapping: 53 },
  "[": { braille: "⠪", keyMapping: 42 },
  "\\": { braille: "⠳", keyMapping: 51 },
  "]": { braille: "⠻", keyMapping: 59 },
  "^": { braille: "⠘", keyMapping: 24 },
};
